const tarotLove = [
    { 
        name: 'O Louco',
        image: '../img/00-TheFool.jpg',
        url: '',
        energy: 'A energia geral desta carta é de muita velocidade e aventuras, representando e inícios ou términos de fases para que surjam novas situações na sua vida. Indica uma situação amorosa onde há muita emoção envolvida e pouquíssima razão. Essa carta normalmente aparece para pessoas que estão conhecendo alguém, não sabem muito bem que este alguém é de fato ou estão muito tomados pelas emoções.',
        question: 'Se você pensou em alguém específico e tirou esta carta querendo saber sobre o que essa pessoa pensa sobre você: esta pessoa ainda está naquele processo de ruminação, com a cabeça um pouco confusa ainda, está conhecendo e decifrando você aos poucos e tem medo de se apegar, pois tende a ser alguém muito emocional, sendo muitas vezes tomado pelas emoções e sentimentos. Por isso, essa pessoa pode ser do tipo libertário, que vive sem amarras e gosta de ter liberdade na vida dele(a). Entretanto, também é também uma pessoa intensa, que se entrega por inteiro, como também cobra por inteiro, podendo se tornar um pouco pegajosa quando realmente ama. De modo geral, essa pessoa ainda está dando os primeiros passos em relação a você e está com a cabeça em outras situações de sua vida neste momento que não tenha muita relação direta com sua vida amorosa. Aproveite para relaxar e deixar as coisas rolarem normalmente, sem pressão e neuras. O que é seu será seu.',
        simNao: 'Esta carta nesta questão simboliza que a situação ainda está um pouco nebulosa, precisa de um pouco mais de tempo e abaixar a poeira para que de fato possa ter uma resposta para esta situação. Por isso, a resposta é um "talvez", afinal, é necessário que a cabeça e o coração de ambos(as) estejam no lugar para alguma evolução nesta situação.',
        conselho: 'O conselho para você que fez esta questão e recebeu essa carta é que você se entregue para as novas situações amorosas da sua vida sem levar aquela bagagem do passado. Mantenha a sabedoria antes de qualquer coisa. Entenda que a vida vai te trazer novidades e vai te colocar em novas situaçôes, mas para isso, você precisa estar aberta(o) para o novo também. Essa carta pede que você se exponha mais e perca o medo de se machucar. Por conta dos traumas, as pessoas tendem a ficar com muito medo de se entregar novamente para outra pessoa. O importante é que você tenha a plena noção de que o outro não deve te completar. Você é quem precisa ser dono de si mesmo e, assim, se libertará do medo da rejeição e abandono e será muito feliz, com ou sem ninguém.'
    },
    { 
        name: 'O Mago',
        image:'',
        url: '',
        energy: 'A energia geral desta carta é de ter autonomia e poder para driblar a situação. Representa uma situação favorável quando sai em uma leitura para a vida amorosa, porque essa carta fala de poder de persuasão e de sedução. O mago seduz pela sua audácia, talento e pela sua inteligência. Por isso, essa carta tende a aparecer em situações onde o consulente e a pessoa amada estão entrando em sintonia. Essa carta tende a aparecer também quando a situação não depende muito da pessoa amada, mas sim de você.',
        question: 'Se você pensou em alguém específico e tirou esta carta, esta pessoa ainda está naquele processo de ruminação, está conhecendo você aos poucos e tem medo de se apegar, pois tende a ser alguém muito emocional, sendo muitas vezes tomado pelas emoções e sentimentos. Por isso, essa pessoa pode ser do tipo libertário, que vive sem amarras e gosta de ter liberdade na vida dele(a). Entretanto, também é também uma pessoa intensa, que se entrega por inteiro, como também cobra por inteiro, podendo se tornar um pouco pegajosa quando realmente ama. De modo geral, essa pessoa ainda está dando os primeiros passos em relação a você e está com a cabeça em outras situações de sua vida neste momento que não tenha muita relação direta com sua vida amorosa. Aproveite para relaxar e deixar as coisas rolarem normalmente, sem pressão e neuras. O que é seu será seu.',
        conselho: 'O conselho para você que fez esta questão e recebeu essa carta é que você se entregue para as novas situações amorosas da sua vida sem levar aquela bagagem do passado. Mantenha a sabedoria antes de qualquer coisa. Entenda que a vida vai te trazer novidades e vai te colocar em novas situaçôes, mas para isso, você precisa estar aberta(o) para o novo também. Essa carta pede que você se exponha mais e perca o medo de se machucar. Por conta dos traumas, as pessoas tendem a ficar com muito medo de se entregar novamente para outra pessoa. O importante é que você tenha a plena noção de que o outro não deve te completar. Você é quem precisa ser dono de si mesmo e, assim, se libertará do medo da rejeição e abandono e será muito feliz, com ou sem ninguém.'
    },
]


